### ISSUE TITLE
Spaces before the require directive cause them to be skipped

### ISSUE THREAD

**Issue by alexdixon** [wiledal/gulp-include#45] opened 2015-08-04 18:37 UTC
I was trying to use some coffeescript from a Rails/Sprockets project, and ran into an issue that took a little while to sort out:

`#= require (...)` doesn't get picked up by gulp-include

while

`#=require (...)` works as expected (no space before the require)

**Comment by wiledal** [comment] 2015-11-26 15:25
Marking this as resolved, as I cannot reproduce.

**Closed by wiledal** 2015-11-26 15:25 UTC
