### ISSUE TITLE
Requiring JS and Coffee files

### ISSUE THREAD

**Issue by juanghurtado** [wiledal/gulp-include#3] opened 2014-01-29 07:45 UTC
Hi there! :wave:

I know which are the purposes of this plugin, but I'm curious to see how you'd solve this situation I'm involved.

Here's the deal:

I want to have a main file which includes all JS and Coffee files needed for the app. Something like this:

``` coffeescript
#= require 'file1.js'
#= require 'file2.coffee'
#= require 'file3.js'
```

Right now this is not possible using `gulp-include` and `gulp-coffee` because the inclusion of the `*.js` files will cause CoffeeScript compilation errors.

How would you solve this need? Maybe making a new Gulp plugin (`gulp-include-coffee`)? I don't like this approach because Gulp plugin are supposed to do just one thing, and do it well.

Maybe giving `gulp-include` an option to set the file extension which will be included? Something like:

``` javascript
gulp.src('./src/app/app.coffee')
  // First parse `app.coffee` file and include only `coffee` files
  .pipe(include({
    extension: '.coffee'
  }))
  // Compile the result with CoffeeScript
  .pipe(coffee())
  // Include the rest of the includes (in the example, plain old JS files)
  .pipe(include())
  .pipe(gulp.dest('./dist/'));
```

I don't know, I'm kind of lost with this… What do you think?

**Comment by jasford** [comment] 2015-05-08 02:15
I know this thread is a little old, but why not just use `gulp-merge` and `gulp-concat` to accomplish what you are looking for. This is how I do it:

```javascript
var gulpMerge = require('gulp-merge');
var concat = require('gulp-concat');
var coffee = require('gulp-coffee');

gulpMerge(
  gulp.src('./assets/js/vendor/*.js')
  gulp.src('./assets/js/app/*.coffee').pipe(coffee()),
  gulp.src('./assets/js/home.js')
)
  .pipe(concat('main.js'))
  .pipe(gulp.dest('dist/js'));
```

This starts up multiple gulp streams and then merges them back together when they are completed. They are then combined to a single file with `gulp-concat` before outputing to the `dist` folder.

**Comment by josh-makalo** [comment] 2016-02-10 22:59
Hi there! Being aware that I'll likely be bashed for reviving such an old bug report, I'd like to offer my two cents to this as well.

How about offering an option to convert certain filetypes before inclusion? Obviously gulp-include wouldn't do the actual conversion itself, instead the user needs to pass the respective converter in the options array. So the user would write something like this:

```javascript
var gulp = require('gulp');
var coffee = require('gulp-coffee');
var include = require('gulp-include');

gulp.src('input.coffee')
  .pipe(include({convert: {"js": coffee()}}))
  .pipe(coffee())
  .pipe(gulp.dest('dist'));
```
gulp-include would then open a new stream for each file to be converted, use the converter as a pipe step and include the stream output into the "input.coffee". In my opinion, this approach adds a powerful and flexible feature to gulp-include without much effort, doesn't require the inclusion syntax to be changed, and solves the original problem. Any thoughts on this?

**Comment by wiledal** [comment] 2016-08-01 16:03
I have completely abandoned `Coffeescript` since the beginning of this plugin, so I'm not super into finding solutions for this. 

I do however do some `babel`-conversions and had issues with mixing es5 vendor files with my application files, which is basically the same issue. You don't want `babel` to recompile `ThreeJS` :).

My solution ended up being a separate compile and concat solution:
```js
var gulp = require('gulp'),
    babel = require('gulp-babel'),
    merge = require('gulp-merge'),
    include = require('gulp-include'),
    concat = require('gulp-concat');

gulp.task('js', function() {
  var vendor = gulp.src('src/vendor/vendor.js')
    .pipe(include());

  var appjs = gulp.src('src/main.js')
    .pipe(include())
    .pipe(babel({
      presets: ['es2015']
    }))
      .on('error', throwError);

  return merge(vendor, appjs)
    .pipe(concat('all.js'))
    .pipe(gulp.dest('dist/js/'));
});
```
It works well and solves any issues regarding cross-compilation of different file types.

**Comment by KenEucker** [comment] 2019-04-07 16:21
Revival:

@juanghurtado any chance you're still interested in this issue? I see that many people jumped in after you experiencing the same issue. 

I also see that there are solutions to getting around this problem without fully relying on gulp-include to make all the things play nicely with each other.

I'm looking for anyone who is presented with this issue, or just feels like they have a solution they can provide, that may be available to help. If not with code then with a test repository that reproduces the issue for others to hack away on. At the very least, it would be good to know if there are at least others who feel that this issue should be resolved by gulp-include.

This issue can stay open for now, but if time passes and no interest is expressed we will archive this request.

**Comment by juanghurtado** [comment] 2019-04-07 19:33
Long time without using Gulp and/or Coffeescript. Can't help much, really.

**Comment by KenEucker** [comment] 2019-04-08 00:41
@juanghurtado No worries, It's totally understandable given that this was first created 5 years ago. Thank you for responding.

I'm going to close this issue for now as I believe that @wiledal's latest comment shows a solution that I think would be a better route to go than to have gulp-include cover this edge case. If this becomes more than an edge case in the future we can reconsider a better solution.

**Closed by KenEucker** 2019-04-08 00:41 UTC
